// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package persistence

type Book struct {
	ID          int64
	Title       string
	Author      string
	Description string
}

type BookGenre struct {
	BookID  int64
	GenreID int64
}

type Favorite struct {
	UserID int64
	BookID int64
}

type Genre struct {
	ID   int64
	Name string
}

type User struct {
	ID       int64
	Username string
	Email    string
	Password string
	Role     string
}
